Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site.py", line 617, in <module>
    main()
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site.py", line 604, in main
    known_paths = addsitepackages(known_paths)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site.py", line 387, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site.py", line 226, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site.py", line 179, in addpackage
    for n, line in enumerate(f):
OSError: [Errno 5] Input/output error
