Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/hhwwgg/QCD_HT500to700_2017/job_9/QCD_HT500to700_2017_executable_job9.py", line 13, in <module>
    run_analysis(config)
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 52, in run_analysis
    events, sum_weights = AnalysisManager.load_events(config["files"], config["branches"])
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 465, in load_events
    with uproot.open(file, timeout = 500) as f:
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/reading.py", line 141, in open
    file = ReadOnlyFile(
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/reading.py", line 580, in __init__
    self._source = Source(
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 272, in __init__
    self._open()
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 275, in _open
    self._resource = XRootDResource(self._file_path, self._timeout)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 83, in __init__
    self._open()
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 92, in _open
    self._xrd_error(status)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 118, in _xrd_error
    raise OSError(
OSError: XRootD error: [ERROR] Operation expired
in file root://cms-xrd-global.cern.ch//store/mc/RunIIFall17NanoAODv7/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8/NANOAODSIM/PU2017_12Apr2018_Nano02Apr2020_102X_mc2017_realistic_v8-v1/60000/19D58E28-8254-3F4C-BD4E-C8CEF7F5A0F7.root
