Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/hhwwgg/GluGluToRadionToHHTo2B2G_M-700_2017/job_5/GluGluToRadionToHHTo2B2G_M-700_2017_executable_job5.py", line 3, in <module>
    from higgs_dna.utils.logger_utils import setup_logger
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/utils/logger_utils.py", line 2, in <module>
    from rich.logging import RichHandler
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/rich/logging.py", line 9, in <module>
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/rich/_log_render.py", line 5, in <module>
    from .text import Text, TextType
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/rich/text.py", line 5, in <module>
    from rich.emoji import EmojiVariant
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/rich/emoji.py", line 4, in <module>
    from .jupyter import JupyterMixin
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/rich/jupyter.py", line 4, in <module>
    from .segment import Segment
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/rich/segment.py", line 21, in <module>
    from .cells import (
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
OSError: [Errno 5] Input/output error
